sudo: required
language: node_js
node_js:
- 7
addons:
  apt:
    source:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - google-chrome-stable
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
    - g++-4.8

services:
- docker

cache:
  pip: true
  directories:
  - node_modules

before_install:
- pip install -U pip --user travis
- pip install flake8 --user travis

install:
- cd $TRAVIS_BUILD_DIR/containers/datalab
- ./build.sh

script:
- cd $TRAVIS_BUILD_DIR/tools/
- flake8 cli/
- cd $TRAVIS_BUILD_DIR/test
- npm install -s -q --depth 0
- npm test
- for i in `ls ui/broken/`; do echo ui/broken/$i; base64 ui/broken/$i; echo \"-----\"; done
- cd ../sources/web/datalab/polymer/test
- export DISPLAY=:99.0
- npm test -- --verbose -l chrome
